# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: "3.7,3.8,3.9"

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        set -xe
        python -VV
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions
        python -m pip install -r tests/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

#    - name: Test with pytest
#      run: |
#        pytest

    - name: "Run tox targets for ${{ matrix.python-version }}"
      run: "python -m tox"

    # We always use a modern Python version for combining coverage to prevent
    # parsing errors in older versions for modern code.
    - uses: "actions/setup-python@v2"
      with:
        python-version: "3.9"

    - name: "Combine coverage"
      run: |
        set -xe
        python -m pip install coverage[toml]
        python -m coverage combine
        python -m coverage xml
      if: "contains(env.USING_COVERAGE, matrix.python-version)"
    - name: "Upload coverage to Codecov"
      if: "contains(env.USING_COVERAGE, matrix.python-version)"
      uses: codecov/codecov-action@v1.0.15
      with:
          fail_ci_if_error: true
